version: '3.1'

services:
 wordpress:
    image: wordpress:4.7.1-php7.0-fpm
    ports:
     - '9000:9000'
    depends_on:
     - db
    environment:
     - WORDPRESS_DB_PASSWORD=password
     - WORDPRESS_DB_USER=root
     - WORDPRESS_DB_HOST=db
    volumes:
     - ./html:/var/www/html
    networks:
      - wp_net
      - x_net
 db:
    image: mariadb
    restart: always
    volumes:
     - ./database:/var/lib/mysql
    environment:
       MARIADB_ROOT_PASSWORD: password
       MARIADB_USER: max
       MARIADB_PASSWORD: 123
       MARIADB_DATABASE: wordpress 
    networks:
      - wp_net
 nginx:
    image: nginx:latest
    depends_on:
      - wordpress
      - db
    networks:
      - x_net
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
      - ./nginx_conf/default.conf:/etc/nginx/conf.d/default.conf

 adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
    networks:
      - wp_net

networks:
 wp_net:
 x_net:
